title: Open Sales and Distribution Model
email: andreas.schlapbach@sbb.ch

description: >- # this means to ignore newlines until "baseurl:"
  Open Sales and Distribution Model to simplify rail distribution.

baseurl: "/OSDM" # the subpath of your site, e.g. /blog

# url: "http://osdm.github.com"

permalink: pretty

favicon: favicon.png

#hide_share_buttons: true
#theme_color: '#eeeeee'

# Build settings
remote_theme: chrisrhymes/bulma-clean-theme

# Don't publish files in the future
future: false

# Measuring hits
google-analytics: UA-185392233-1

plugins:
  - jekyll-analytics
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  - kramdown-parser-gfm

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

markdown: kramdown
