openapi: 3.0.0
info:
  version: 1.0.0
  title: UIC 90918-10
  description: compensate booking or prebooking
  contact:
    name: UIC
    url: https://www.uic.org
    email: uic@uic.org
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  '/{version}/bookings/{bookingId}':
    delete:
      description: compensate booking
      operationId: compensateBooking
      parameters:
        - name: version
          in: path
          description: schema version
          required: true
          schema:
            type: string
        - name: bookingId
          in: path
          description: id of the booking
          required: true
          schema:
            type: string
      responses:
        '200':
          description: compensation ok
        '404':
          description: booking does not exist
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '../schemas/osdm-common-schema-v2#/definitions/ErrorDef'